### ISSUE TITLE
Plugin doesn't appear to work when config includes "prefix" property

### ISSUE THREAD

**Issue by gobrendan** [tailwindlabs/tailwindcss-container-queries#13]
### What version of @tailwindcss/container-queries are you using?

3.3.1

### What version of Node.js are you using?

Tailwind Play

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

https://play.tailwindcss.com/PL5t2J58Lw

### Describe your issue

When using the prefix property in the config, the plugin doesn't appear to work. In this Play example, if you comment-out the prefix property, the first "test" word will be underlined properly.

https://play.tailwindcss.com/PL5t2J58Lw

I really like this plugin. Just hoping to get it working when a prefix is used.

Thanks!

**Comment by thecrypticace** [comment]
Hey! This is because you also need to prefix the `@container` utility: `m-@container`.

Here's a Tailwind Play of that working: https://play.tailwindcss.com/Uj3qcNblAa

**Comment by gobrendan** [comment]
Ah, got it! Thanks so much!
