### ISSUE TITLE
Wrong installation command

### ISSUE THREAD

**Issue by smith558** [tailwindlabs/tailwindcss-container-queries#28]
### What version of @tailwindcss/container-queries are you using?

N/A

### What version of Node.js are you using?

N/A

### What browser are you using?

N/A

### What operating system are you using?

N/A

### Reproduction repository

N/A

### Describe your issue

Should the installation command not be `npm install -D @tailwindcss/container-queries`?

**Comment by adamwathan** [comment]
Kinda up to you! I generally only install things like test runners, linters, etc. as dev dependencies. Everything gets bundled so really everything can be a dev dependency, so the distinction in bundled web apps is sort of pointless. Neither option is wrong, just preference or depends on the tooling you're using 👍

**Comment by smith558** [comment]
Fair enough. Might still be worth updating just to be consistent with other taiwildcss official plugins which use `-D`.
