### ISSUE TITLE
Fallback for Container Queries

### ISSUE THREAD

**Issue by Serator** [tailwindlabs/tailwindcss-container-queries#8]
### What version of @tailwindcss/container-queries are you using?

v0.1.0

### What version of Node.js are you using?

-

### What browser are you using?

Chrome 109.0.5414.75

### What operating system are you using?

Windows 10

### Reproduction repository

https://play.tailwindcss.com/ksciGipiQh

### Describe your issue

I would like to add a fallback option in case Container Queries are not supported.
`supports-[container-type:_inline-size]:@lg/someName:modern_styles` & `@lg:fallback_styles` looks like a good choice for this purpose. The problem is that the styles `@lg:` override the `supports-...` styles.

![image](https://user-images.githubusercontent.com/625005/213251004-dcf400d2-4d51-4e8b-b354-ba588810dd05.png)

The workaround may be `!important` or `supports-[not...`, but this solution is not always possible.

**Comment by adriannecris** [comment]
Have you use a polyfill? Either use https://github.com/ausi/cq-prolyfill or https://github.com/GoogleChromeLabs/container-query-polyfill

**Comment by Serator** [comment]
`not-cq' makes sense, thanks!
